name: Automerge-develop

on:
  workflow_dispatch:
  schedule:
    # You can setup schedule here
    - cron: '*/15 * * * *' # Sync every 15 minutes

env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://Bit-fire:${{secrets.GITHUB_TOKEN}}@github.com/Bit-fire/Ronja.js.git

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: develop

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/YetAnotherGerrit/Ronja.js.git

  # replace "master" with your master branch name
  MASTER_BRANCH: develop

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with master
      run: |
        # Clone MY repository and check out MY branch in folder "tmp"
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp

        cd tmp
        git config user.name "Automerge Bot"
        git config user.email "bot@example.com"

        # Disable Git default behavior to rebase any local changes on top of the changes being pulled in
        # git config pull.rebase false

        # Pull changes from MASTER branch into the local copy
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}

        # Push any changes made to the local copy of MY repository to MY remote repository
        git push
